process.env.SESSION_DATA_DIR = require('node:fs').mkdtempSync(require('node:path').join(require('node:os').tmpdir(), 'sigaa-session-fixture-'));
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawn } = require('node:child_process');
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'sigaa-exams-'));
process.env.SECRET = 'test-only-exams-secret';
process.env.ENC_SECRET = 'a'.repeat(32);
process.env.ENC_SECRET_USER = 'b'.repeat(32);
process.env.EXAM_DATA_DIR = path.join(directory, 'data');
process.env.EXAM_CACHE_DIR = path.join(directory, 'cache');
process.env.TOKEN_REVOCATION_DIR = path.join(directory, 'revocations');
delete process.env.VERCEL;
delete process.env.UPSTASH_REDIS_REST_URL;
delete process.env.UPSTASH_REDIS_REST_TOKEN;
fs.mkdirSync(process.env.EXAM_CACHE_DIR);
fs.writeFileSync(path.join(process.env.EXAM_CACHE_DIR, 'provas_computacao.json'), '[{"titulo":"legacy"}]');
fs.writeFileSync(path.join(process.env.EXAM_CACHE_DIR, 'calendario_computacao.json'), JSON.stringify({ eventos: [{ data: '2026-12-20', tipo: 'fim-aulas', titulo: 'Fim das aulas' }] }));
const auth = require('../api/auth');
const exams = require('../lib/manual-exams');
const handler = require('../api/calendario-eventos');
function response() { return { setHeader() {}, status(code) { this.code = code; return this; }, json(body) { this.body = body; return this; }, end() {} }; }
const institution = { 'Nome do Usuario': 'Aluno de teste', Curso: 'Engenharia de Computação' };
const schedule = [{ semestre: '2026.2', disciplina: 'Matemática', turma: '01' }];
test('manual exams require verified SIGAA access, share the cap, isolate classes and retire old terms', async () => {
    const a = auth.gerarTokenLogin({ user: 'student-a', pass: 'test' });
    const b = auth.gerarTokenLogin({ user: 'student-b', pass: 'test' });
    const c = auth.gerarTokenLogin({ user: 'student-c', pass: 'test' });
    let res = response();
    await handler({ method: 'POST', headers: {}, body: {}, query: {} }, res);
    assert.equal(res.code, 401);
    res = response();
    await handler({ method: 'POST', headers: { authorization: `Bearer ${a}` }, body: {}, query: {} }, res);
    assert.equal(res.code, 403, 'minting a JWT does not confirm enrollment');
    assert.equal(fs.existsSync(path.join(process.env.EXAM_CACHE_DIR, 'provas_computacao.json')), false);
    assert.equal(exams.officialEvents('computacao').length, 1);
    assert.equal(await exams.recordAcademicAccess(a, {}, schedule, []), null);
    const verified = await exams.recordAcademicAccess(a, institution, schedule, []);
    await exams.recordAcademicAccess(b, institution, schedule, []);
    await exams.recordAcademicAccess(c, institution, [{ ...schedule[0], turma: '02' }], []);
    const aa = await exams.getAccess(a), bb = await exams.getAccess(b), cc = await exams.getAccess(c);
    const body = { turmaId: verified.turmasParaProvas[0].id, data: '2026-11-10', titulo: 'Prova 1' };
    assert.equal(exams.add(cc, body).status, 403);
    for (let i = 0; i < 6; i++) assert.equal(exams.add(i % 2 ? aa : bb, { ...body, titulo: `Prova ${i}` }).status, 200);
    assert.equal(exams.add(aa, { ...body, titulo: 'Sétima prova' }).status, 409);
    assert.equal(exams.add(bb, { ...body, titulo: 'Prova 0' }).status, 200, 'duplicate does not consume quota');
    const listed = exams.list(aa, 'computacao');
    assert.equal(listed.turmas[0].provasCadastradas, 6);
    assert.equal(listed.eventos.filter(e => e.porOutroUsuario).length, 3);
    assert.equal(exams.list(cc, 'computacao').eventos.length, 0);
    assert.ok(!JSON.stringify(listed).includes('student-'));
    const concurrent = await Promise.all(Array.from({ length: 8 }, (_, i) => new Promise((resolve, reject) => {
        const child = spawn(process.execPath, ['-e', `let input='';process.stdin.on('data',d=>input+=d);process.stdin.on('end',async()=>{const p=JSON.parse(input);const e=require('./lib/manual-exams');const a=await e.getAccess(p.token);console.log(e.add(a,p.body).status);});`], { cwd: path.resolve(__dirname, '..'), env: process.env });
        let output = '', errors = '';
        child.stdout.on('data', d => output += d);
        child.stderr.on('data', d => errors += d);
        child.on('error', reject);
        child.on('close', code => code === 0 ? resolve(Number(output.trim())) : reject(new Error(errors)));
        child.stdin.end(JSON.stringify({ token: c, body: { ...body, turmaId: cc.classes[0].id, titulo: `Concurrent ${i}` } }));
    })));
    assert.equal(concurrent.filter(status => status === 200).length, 6);
    assert.equal(concurrent.filter(status => status === 409).length, 2);
    assert.equal(exams.list(cc, 'computacao').eventos.length, 6);
    assert.equal(exams.add(aa, { ...body, data: '2026-12-21' }).status, 400);
    assert.equal(exams.add(aa, { ...body, data: '2026-02-30' }).status, 400);
    await auth.revogarTokenLogin(b);
    assert.equal(await exams.getAccess(b), null);
    await exams.recordAcademicAccess(a, institution, [{ ...schedule[0], semestre: '2027.1' }], []);
    assert.equal(exams.list(await exams.getAccess(a), 'computacao').eventos.length, 0);
    assert.equal((await exams.getAccess(c)).classes.length, 0);
});
